server.port=9070
spring.application.name=larcash-api
#spring.config.import=optional:classpath:env.properties

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

#jdbc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#actuator
management.endpoints.web.exposure.include=health, env, metrics, info
management.endpoint.health.show-details=ALWAYS
